#!/bin/busybox sh

# Mount /proc and /sys filesystems
mount -t proc none /proc
mount -t sysfs none /sys

# NIC up
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip link set lo up

sleep 0.5

setsid sh -c 'exec sh -l </dev/ttyS0 >/dev/ttyS0 2>&1'
